### ISSUE TITLE
Document vacation policy and how we manage it

### ISSUE THREAD

**Issue by knolleary** [flowforge/handbook#10]
We have an unlimited vacation policy. Easy to say, but it does need some guidelines around it that should get documented.

We also need to formalise how we track time-off so that:

 - we ensure employees are taking vacation for their own good
 - we have somewhere employees can indicate their planned absence to help with ongoing planning activities

The Pilot/BambooHR tooling does have a way to 'request time off' - but it isn't clear how that is managed and I haven't been able to find an overview of all employees. Plus we can't assume everyone will be hired via Pilot.

To date we have use a shared team calendar ("FlowForge Team Events") - where team members can add all-day events to indicate when they are out of office. That helps with scheduling. Downside is we have to remember to add each employee to the ACL for the calendar - will add an item to the onboarding checklist for it.

**Comment by sammachin** [comment]
There are certain requirements (in the UK at least) for employees to take a minimum number of days, and as a company you need to be able to show that you're monitoring that. Seeing as pilot gives the minimum days we should encourage people to book at least some of their time off in there as well as the calendar. 
Last year I put my "proper" holidays of more than a week or so into Pilot in order to use all the days, but for the odd one-day things I just used the calendar.
